export { Header } from './Header/Header';
export { Footer } from './Footer/Footer';
export { TopRatedMoviesLayout } from './TopRated/Layout';
export { TopRatedShowsLayout } from './TopRated/TvShowLayout';
export { Pagination } from './Pagination/Pagination';
export { TvShowsPagination } from './Pagination/TvShowPagination'
export { MoviesLayout } from './Layouts/MovieLayout';
export { TvShowsLayout } from './Layouts/TvShowsLayout';
export { Popup } from './Popup/Popup';
export { MovieDetail } from './Details/MovieDetails';
export { TvShowDetail } from './Details/TvShowDetails';